---
- name: Render cf template
  template:
    src: create_vpc.yml.j2
    dest: /tmp/create_vpc.yml

- name: 'Create VPC'
  cloudformation:
    stack_name: "{{ stack_name|default('LabStack') }}"
    state: present
    region: "{{ region|default(omit) }}"
    template_body: "{{ lookup ('template', 'create_vpc.yml.j2') }}"
    tags:
      stack_name: "{{ stack_name|default('LabStack') }}"
  #register: "vpc_{{ stack_name|default('LabStack') }}_info"
