---
- name: Render cf template
  template:
    src: create_vpc.yml.j2
    dest: /tmp/create_vpc.yml

- name: 'Create VPC'
  cloudformation:
    stack_name: "{{ stack_name|default('LabStack') }}"
    state: present
    region: "{{ region|default(omit) }}"
    template_body: "{{ lookup ('template', 'create_vpc.yml.j2') }}"
    tags:
      stack_name: "{{ stack_name|default('LabStack') }}"
  register: "vpc_stack_info"

- name: set_fact vpc stack
  set_fact:
    vpcstackinfo: "{{ vpc_stack_info }}"

- name: set_fact public subnets
  set_fact:
    publicsubnetids: "{{ vpc_stack_info.stack_resources|to_json|from_json|json_query(match_public) }}"
  vars:
    match_public: "[?contains(logical_resource_id, 'publicsubnet')].physical_resource_id"

- name: set_fact VPC
  set_fact:
    vpcid: "{{ vpc_stack_info['stack_resources']|json_query(match_vpc)|first }}"
  vars:
    match_vpc: "[?resource_type=='AWS::EC2::VPC'].physical_resource_id"
